# Generated by Django 3.0.7 on 2020-06-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbitflames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
