# Generated by Django 3.0.7 on 2020-07-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbitflames', '0003_auto_20200620_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
